# Shared aliases and functions for bash and zsh

alias ll='ls -la'
alias gs='git status'
alias gp='git push'
alias gl='git pull'

gc() { git commit -m "$*"; }

mkcd() { mkdir -p "$1" && cd "$1"; }

extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.gz|*.tgz) tar xvzf "$1" ;;
            *.tar.bz2|*.tbz2) tar xvjf "$1" ;;
            *.tar.xz|*.txz) tar xvJf "$1" ;;
            *.tar) tar xvf "$1" ;;
            *.zip) unzip "$1" ;;
            *.rar) unrar x "$1" ;;
            *.7z) 7z x "$1" ;;
            *) echo "Unsupported file format" ;;
        esac
    else
        echo "File not found: $1"
    fi
}

# kubectl shorthand: use kubecolor if available
k() {
    if command -v kubecolor &>/dev/null; then
        kubecolor "$@"
    else
        kubectl "$@"
    fi
}

# ls: use lsd if available
if command -v lsd &>/dev/null; then
    alias ls='lsd'
fi

# cat: use bat if available (set in rc files as function to pass args)

# thefuck alias
if command -v thefuck &>/dev/null; then
    alias f='fuck'
fi

# mkpass: create random password
mkpass() {
    if [ -n "$1" ]; then
        openssl rand -hex "$1"
    else
        openssl rand -hex 12
    fi
}

# commit: conventional commits
# commit feat terraform update lock => feat(terraform): update lock
# commit feat! terraform update lock => feat(terraform)!: update lock
# commit chore^ update README => chore: update README
# commit fix!^ rename README => fix!: rename README
commit() {
    local commit_message
    if [ $# -gt 0 ]; then
        local commit_type="$1"
        shift
        if case "$commit_type" in *!^) true;; *) false;; esac; then
            commit_type="${commit_type%!^}"
            commit_message="$commit_type!: $*"
        elif case "$commit_type" in *^) true;; *) false;; esac; then
            commit_type="${commit_type%^}"
            commit_message="$commit_type: $*"
        else
            local commit_scope="$1"
            shift
            local breaking=""
            case "$commit_type" in *!) breaking="!"; commit_type="${commit_type%!}"; esac
            commit_message="$commit_type($commit_scope)$breaking: $*"
        fi
        git commit -s -m "$commit_message"
    else
        commit_message="chore: $(curl -s http://whatthecommit.com/index.txt)"
        git commit -s -m "$commit_message" -m "Commit generated by whatthecommit.com"
    fi
    if command -v lolcat &>/dev/null; then
        printf '\nCommit message ~ "%s"\n' "$commit_message" | lolcat
    else
        printf '\nCommit message ~ "%s"\n' "$commit_message"
    fi
}
